### ISSUE TITLE
TASK Create DraftPresentation Task

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#10]
#### References
- [ ] Research M2Doc for PPTX

#### Task Steps/Actions
- [ ] Create implementation
    - [ ] Integrate AgendaWalker
        - [ ] Update DraftPresentation integration tests
        - [ ] Perform tests
        - [ ] Commit Update
    - [ ] Create LaTeXPresentationVisitor
        - [ ] Create unit tests
        - [ ] Update DraftPresentation integration tests
        - [ ] Perform tests
        - [ ] Commit Update
    - [ ] Create MS Powerpoint visitor
        - [ ] Create unit tests
        - [ ] Update DraftPresentation integration tests
        - [ ] Perform tests
        - [ ] Commit update
- [ ]  Create unit tests
- [ ] Create integration tests
- [ ] Update MeetingsPlugin
- [ ] Add integration testes to MeetingsPlugin
- [ ] Add functional tests to MeetingsPlugin
- [ ] Perform tests
- [ ] Commit update
