### ISSUE TITLE
TASK Create InitMeeting Task

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#11]
#### Task Description
Create a task that initializes an empty meeting project.

#### Task Steps/Actions
- [ ] Create implementation [InitMeeting.java](meetings-plugin/src/main/java/setools/gradle/tasks/InitMeeting.java)
- [ ]  Create unit tests [InitMeetingUnitTest.java](meetings-plugin/src/main/java/setools/gradle/tasks/InitMeetingUnitTest.java)
- [ ] Update [MeetingsPlugin.java](meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsPlugin.java) 
- [ ] Add unit testes to [MeetingsPluginUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugin/MeetingsPluginUnitTest.java)
- [ ] Add integration testes to [MeetingsPluginIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugin/MeetingsPluginIntegrationTest.java)
- [ ] Add functional testes to [MeetingsPluginFunctionalTest.java](meetings-plugin/src/functional-test/java/setools/gradle/plugin/MeetingsPluginFunctionalTest.java)
- [ ] Perform tests
- [ ] Commit update
