### ISSUE TITLE
TASK

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#12]
#### Task Description
Create a task to publish approved minutes.

#### Task Steps/Actions
- [ ] Create implementation [PublishMinutes.java](meetings-plugin/src/main/java/setools/gradle/tasks/PublishMinutes.java)
- [ ]  Create unit tests [PublishMinutesUnitTest.java](meetings-plugin/src/main/java/setools/gradle/tasks/PublishMinutesUnitTest.java)
- [ ] Create integration tests [PublishMinutesInterationTest.java](meetings-plugin/src/main/java/setools/gradle/tasks/PublishMinutesIntegrationTest.java)
- [ ] Update [MeetingsPlugin.java](meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsPlugin.java) 
- [ ] Add unit testes to [MeetingsPluginUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugin/MeetingsPluginUnitTest.java)
- [ ] Add integration testes to [MeetingsPluginIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugin/MeetingsPluginIntegrationTest.java)
- [ ] Add functional testes to [MeetingsPluginFunctionalTest.java](meetings-plugin/src/functional-test/java/setools/gradle/plugin/MeetingsPluginFunctionalTest.java)
- [ ] Perform tests
- [ ] Commit update
