### ISSUE TITLE
TASK Create Release Commit

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#13]
#### Task Description
Perform final testing and prepare merge request for release.

#### References
- [ ] Add information on PIT testing.

#### Task Steps/Actions
- [ ] Create testing branch from feature
- [ ] Develop PIT Testing
- [ ] Perform testing
- [ ] Perform manual testing
- [ ] Validate all test results
- [ ] Draft test report
- [ ] Draft release document(s)
- [ ] Commit release version
- [ ] Merge into master
- [ ] Create release tag 0.1.0
