### ISSUE TITLE
TASK Create meetings-plugin project

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#16]
#### References
Add Markdown list of references (i.e. research) necessary to complete Task Steps/Actions.  Provide links where possible.

#### Task Steps/Actions
- [ ] Create [meetings-plugin/build.gradle](../meetings-plugin/build.gradle)
- [ ] Update [settings.gradle](../settings.gradle)
- [ ] Test empty project build
- [ ] Commit baseline project to new branch feature/meetings-plugin
