### ISSUE TITLE
TASK Create MeetingsLifecyclePlugin

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#17]
#### Task Description
Create a plugin with default tasks that represent the lifecycle phases of a generic meeting.

#### References
Add Markdown list of references (i.e. research) necessary to complete Task Steps/Actions.  Provide links where possible.

#### Task Steps/Actions
- [x] Create [MeetingsLifecyclePlugin.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsLifecyclePlugin.java)
    - [x] Configure DraftAgenda Task
    - [x] Configure DraftMinutes Task
    - [x] Configure DraftPresentation Task
    - [x] Configure AssemblePresentation Task
    - [x] Configure PublishPresentation Task
    - [x] Configure PublishMinutes Task
- [x] Create [AbstractMeetingsPluginUnitTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/test/java/setools/gradle/plugin/AbstractMeetingsPluginUnitTest.java)
    - [x] Verify DraftAgenda Task is applied
    - [x] Verify DraftMinutes Task is applied
    - [x] Verify DraftMinutes Task depends on DraftAgenda
    - [x] Verify DraftPresentation Task is applied
    - [x] Verify DraftPresentation Task depends on DraftAgenda
    - [x] Verify AssemblePresentation Task is applied
    - [x] Verify AssemblePresentation Task depends on DraftPresentation
    - [x] Verify PublishPresentation Task is applied
    - [x] Verify PublishPresentation Task depends on AssemblePresentation
    - [x] Verify PublishMinutes Task is applied
    - [x] Verify PublishMinutes Task depends on PublishPresentation
- [x] Test
- [x] Commit
