### ISSUE TITLE
TASK Create an AbstractMeetingsPlugin

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#18]
#### Task Description
Create a plugin that abstracts common functionality of a MeetingsPlugin.

#### References
Add Markdown list of references (i.e. research) necessary to complete Task Steps/Actions.  Provide links where possible.

#### Task Steps/Actions
- [ ] Create [AbstractMeetingsPlugin.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/main/java/setools/gradle/plugin/AbstractMeetingsPlugin.java)
    - [ ] Apply MeetingsLifecyclePlugin
    - [ ] Configure MeetingsPluginExtension using DefaultMeetingsPluginExtension
    - [ ] Create method to replace DraftAgenda Task with concrete task
    - [ ] Create method to replace DraftMinutes Task with concrete task
    - [ ] Create method to replace DraftPresentation Task with concrete task
    - [ ] Create method to replace AssemblePresentation Task with concrete task
    - [ ] Create method to replace PublishPresentation Task with concrete task
    - [ ] Create method to replace PublishMinutes Task with concrete task
- [ ] Create [AbstractMeetingsPluginUnitTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/test/java/setools/gradle/plugin/AbstractMeetingsPluginUnitTest.java)
    - [ ] Verify MeetingsLifecyclePlugin is applied
    - [ ] Verify MeetingsPluginExtension is configured
    - [ ] Verify default task replacements
- [ ] Create [AbstractMeetingsPluginIntegrationTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/integration-test/java/setools/gradle/plugin/AbstractMeetingsPluginIntegrationTest.java)
    - [ ] Verify MeetingsLifecyclePlugin is applied
    - [ ] Verify MeetingsPluginExtension is configured
    - [ ] Verify DraftAgenda configuration based on MeetingsPluginExtension
    - [ ] Verify DraftMinutes configuration based on MeetingsPluginExtension
    - [ ] Verify DraftPresentation configuration based on MeetingsPluginExtension
    - [ ] Verify AssemblePresentation configuration based on MeetingsPluginExtension
    - [ ] Verify PublishPresentation configuration based on MeetingsPluginExtension
    - [ ] Verify PublishMinutes configuration based on MeetingsPluginExtension
- [ ] Create [AbstractMeetingsPluginFunctionalTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/functional-test/java/setools/gradle/plugin/AbstractMeetingsPluginFunctionalTest.java)
    - [ ] Verify default configuration and execution
    - [ ] Verify execution based on custom MeetingsPluginExtension configurations
        - [ ] Test setting custom meeting name
        - [ ] Test setting custom meeting description
        - [ ] Test setting custom meeting date
        - [ ] Test setting custom agenda
        - [ ] Test setting custom output names
        - [ ] Test setting custom publishing
- [ ] Test
- [ ] Commit
