### ISSUE TITLE
TASK Create LaTexMeetingsPlugin

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#19]
#### Task Description
Create a plugin that abstracts common functionality of a MeetingsPlugin.

#### References
Add Markdown list of references (i.e. research) necessary to complete Task Steps/Actions.  Provide links where possible.

#### Task Steps/Actions
- [ ] Create [LaTexMeetingsPlugin.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/main/java/setools/gradle/plugin/LaTexMeetingsPlugin.java)
    - [ ] Configure MeetingsPluginExtension using DefaultMeetingsPluginExtension
    - [ ] Override replaceDraftAgenda Task
    - [ ] Override replaceDraftMinutes Task
    - [ ] Override replaceDraftPresentation Task
    - [ ] Override replaceAssemblePresentation Task
    - [ ] Override replacePublishPresentation Task
    - [ ] Override replacePublishMinutes Task
- [ ] Create [LaTexMeetingsPluginUnitTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/test/java/setools/gradle/plugin/LaTexMeetingsPluginUnitTest.java)
- [ ] Create [LaTexMeetingsPluginIntegrationTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/integration-test/java/setools/gradle/plugin/LaTexMeetingsPluginIntegrationTest.java)
- [ ] Create [LaTexMeetingsPluginFunctionalTest.java](https://github.com/mfisch2011/setools/blob/feature/latex-meetings-plugin/meetings-plugin/src/functional-test/java/setools/gradle/plugin/LaTexMeetingsPluginFunctionalTest.java)
- [ ] Test
- [ ] Commit
