### ISSUE TITLE
TASK - Create sub-project

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#4]
#### Task Description
Create and test build script for subproject.

#### Task Steps/Actions
- [x] Create [build.gradle](meetings-plugin/build.gradle)
- [x] Create source sets.
    - [x] [src/main/java](meetings-plugin/src/main/java)
    - [x] [src/main/resources](meetings-plugin/src/main/resources)
    - [x] [src/test/java](meetings-plugin/src/test/java)
    - [x] [src/test/resources](meetings-plugin/src/test/resources)
    - [x] [src/integration-test/java](meetings-plugin/src/integration-test/java)
    - [x] [src/integration-test/resources](meetings-plugin/src/integration-test/resources)
    - [x] [src/functional-test/java](meetings-plugin/src/functional-test/java)
    - [x] [src/functional-test/resources](meetings-plugin/src/functional-test/resources)
- [x] Run test build to validate
- [x] Merge into feature/meetings-plugin branch.
