### ISSUE TITLE
TASK Initialize Project

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#42]
### Task Name
Initialize Project

#### Task Description
Create structured Gradle project with conventions for java  libraries, java applications, and Gradle plugins.

#### References
N/A

#### Task Steps/Actions
- [x] Initialize structured Gradle project.
     - [x] Run gradle init.
     - [x] Test build.
     - [x] [Commit (5d7c60e).](https://github.com/mfisch2011/setools/commit/5d7c60eb1bf4483239fa281062819eb42c9bc1a1)
- [x] Create base build conventions.
     - [x] Create base-conventions.gradle.
     - [x] Test build.
     - [x] [Commit (c676a9c).](https://github.com/mfisch2011/setools/commit/c676a9c73bac390810131669a712f87ab40ffcee)
- [x] Add versioner plugin.
     - [x] Update base-conventions.gradle.
     - [x] Update buildSrc/build.gradle.
     - [x] Test build.
     - [x] [Commit (22c7cfb).](https://github.com/mfisch2011/setools/commit/22c7cfb6e9580206d7c572125606452856cf57b4)
- [x] Add test commit revert plugin.
     - [x] Update base-conventions.gradle.
     - [x] Update buildSrc/build.gradle.
     - [x] Test build.
     - [x] [Commit (d3f3197).](https://github.com/mfisch2011/setools/commit/d3f3197ebd56315dc409231e1b585d4fe2b3cbe7)
- [x] Add JaCoCo plugin.
     - [x] Update java-common-conventions.gradle.
     - [x] Test build.
     - [x] [Commit (d0904f0).](https://github.com/mfisch2011/setools/commit/d0904f01f3fafd6391d1f1f7791cc67596b88f4b)
- [x] Add SpotBug plugin.
     - [x] Update java-common-conventions.gradle.
     - [x] Update buildSrc/build.gradle.
     - [x] Test build.
     - [x] [Commit. (f390e2b)](https://github.com/mfisch2011/setools/commit/f390e2b4c3c94add8fb015733e54f4489a0da099)
- [x] Add Maven Publishing plugin.
     - [x] Update base-conventions.gradle.
     - [x] Update java-common-conventions.gradle.
     - [x] Test build.
     - [x] [Commit (21d8186).](https://github.com/mfisch2011/setools/commit/21d8186d8f3c2f4c58c10a3d714be5f0095b889e)
- [x] Create plugin project conventions.
     - [x] Create gradle-plugin-conventions.gradle.
     - [x] Test build.
     - [x] [Commit (a97b40b).](https://github.com/mfisch2011/setools/commit/a97b40b14a82c6d0beb6a2c348aebb0e8f03ba89)
- [x] Document source.
