### ISSUE TITLE
TASK MeetingBasePlugin

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#43]
### Task Name
MeetingBasePlugin

#### Task Description
Create a plugin for automating basic tasks for general meetings and working groups.

#### References
N/A
#### Task Steps/Actions
- [x] Create feature/meetings-base-plugin branch.
- [ ] Create api/meetings-base-plugin.
     - [x] Create build.gradle.
     - [ ] [Create Meetings API.](https://github.com/mfisch2011/setools/issues/45)
     - [ ] Create Meetings Tasks.
     - [ ] Create abstract Meetings Registration Callback.
     - [ ] Create MeetingsBasePlugin.
- [ ] Document source.
- [ ] Merge into dev.
