### ISSUE TITLE
TASK MeetingOoxmlPlugin

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#44]
### Task Name
MeetingOoxmlPlugin

#### Task Description
Create a meeting plugin for MS Office documents extending BaseMeetingsPlugin.

#### References
N/A
#### Task Steps/Actions
- [ ] Create feature/meetings-ooxml-plugin branch.
- [ ] Create plugins/meetings-ooxml-plugin.
     - [ ] Create build.gradle.
     - [ ] Create Meetings MS Office Tasks.
     - [ ] Create Meetings MS Office Registration Callback.
     - [ ] Create MeetingsOoxmlPlugin.
- [ ] Document source.
- [ ] Merge into dev.
