### ISSUE TITLE
TASK Create Meetings API

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#45]
### Task Name
Create Meetings API

#### Task Description
Create an API to describe settings and configuration for general meetings and working groups.

#### Task Steps/Actions
- [x] Create setools.gradle.meetings.dsl package. 
- [ ] MeetingHandler
     - [x] Create MeetingsHandler interface.
     - [x] Test build.
     - [x] [Commit. (c6a43a7)](https://github.com/mfisch2011/setools/commit/c6a43a7ab9edddab6fc7163d83f789f67e46312e)
     - [x] Create MeetingsHandler abstract test.
     - [ ] Test build.
     - [ ] Commit.
     - [ ] Create DefaultMeetingsHandler implementation.
     - [ ] Test build.
     - [ ] Commit.
     - [ ] Create DefaultMeetingsHandlerTest implementation.
     - [ ] Test build.
     - [ ] Commit.
- [ ] Meeting
     - [x] Create Meeting interface.
     - [x] Test build.
     - [x] Commit.
     - [x] Create MeetingTest abstract test.
     - [x] Test build.
     - [x] Commit.
     - [ ] Update Meeting with Agenda
          - [x] Update Meeting interface.
          - [x] Create AgendaHandler.
          - [x] Test Build.
          - [x] Commit.
          - [x] Create AgendaHandler abstract unit test.
          - [x] Test build.
          - [x] Commit.
          - [x] Create Topic interface
          - [x] Test build.
          - [x] Commit.
          - [ ] Create TopicTest abstract unit test.
          - [ ] Test build.
          - [ ] Commit.
     - [x] Update Meeting with Attendees
          - [x] Update Meeting interface.
          - [x] Create AttendeesHandler interface.
          - [x] Test build.
          - [x] Commit.
          - [x] Create AttendeesHandler abstract unit test.
          - [x] Test build.
          - [x] Commit.
          - [x] Create DefaultAttendeesHandler implementation.
          - [x] Test build.
          - [x] Commit.
          - [x] Create DefaultAttendeesHandlerTest implementation.
          - [x] Test build.
          - [x] Commit.
          - [x] Create Attendee interface.
          - [x] Test build.
          - [x] Commit.
          - [x] Create AttendeeTest abstract unit test.
          - [x] Test build.
          - [x] Commit.
          - [x] Create DefaultAttendee implementation.
          - [x] Test build.
          - [x] Commit.
          - [x] Create DefaultAttendeeTest implementation.
          - [x] Test build.
          - [x] Commit.
     - [ ] Create DefaultMeeting implementation.
     - [ ] Test build.
     - [ ] Commit.
     - [ ] Create DefaultMeetingTest implementation.
     - [ ] Test build.
     - [ ] Commit.
- [ ] WorkingGroup
     - [x] Create WorkingGroup interface.
     - [x] Test build.
     - [x] Commit.
     - [x] Create WorkingGroupTest abstract unit test.
     - [x] Test build.
     - [x] Commit.
     - [ ] Create DefaultWorkingGroup implementation.
     - [ ] Test build.
     - [ ] Commit.
     - [ ] Create DefaultWorkingGroupTest implementation.
     - [ ] Test build.
     - [ ] Commit.
