### ISSUE TITLE
TASK Create MeetingsPlugin Class

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#5]
#### Task Description
Create the skeleton implementation of MeetinsPlugin.

#### Task Steps/Actions
- [ ] Create plugin implementation [MeetingsPlugin.java](meetings-plugin/src/main/java/setools/gradle/plugins/MeetingsPlugin.java)
- [ ] Create plugin unit tests [MeetingsPluginUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugins/MeetingsPluginUnitTest.java)
- [ ] Create plugin integration tests [MeetingsPluginIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugins/MeetingsPluginIntegrationTest.java)
- [ ] Create plugin functional tests [MeetingsPluginFunctionalTest.java](meetings-plugin/src/functional-test/java/setools/gradle/plugins/MeetingsPluginFunctionalTest.java)
- [ ] Perform tests to validate
- [ ] Commit update
