### ISSUE TITLE
TASK Create Draft Agenda Task

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#6]
#### Task Steps/Actions
- [ ] Create implementation [DraftAgenda.java](meetings-plugin/src/main/java/setools/gradle/tasks/DraftAgenda.java)
- [ ]  Create unit tests [DraftAgendaUnitTest.java](meetings-plugin/src/main/java/setools/gradle/tasks/DraftAgendaUnitTest.java)
- [ ] Create integration tests [DraftAgendaIntegrationTest.java](meetings-plugin/src/main/java/setools/gradle/tasks/DraftAgendaIntegrationTest.java)
- [ ] Update [MeetingsPlugin.java](meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsPlugin.java) 
- [ ] Add unit testes to [MeetingsPluginUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugin/MeetingsPluginUnitTest.java)
- [ ] Add integration testes to [MeetingsPluginIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugin/MeetingsPluginIntegrationTest.java)
- [ ] Add functional testes to [MeetingsPluginFunctionalTest.java](meetings-plugin/src/functional-test/java/setools/gradle/plugin/MeetingsPluginFunctionalTest.java)
- [ ] Perform tests
- [ ] Commit update
