### ISSUE TITLE
TASK Create MeetingsPluginExtension

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#7]
#### Task Steps/Actions
- [ ] Create extension interface [MeetingsPluginExtension.java](meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsPluginExtension.java)
    - [ ] Meeting Name
    - [ ] Meeting Date
    - [ ] Attendees List
    - [ ] Meeting Agenda
- [ ] Create extension implementation [DefaultMeetingsPluginExtension.java](meetings-plugin/src/main/java/setools/gradle/plugin/internal/DefaultMeetingsPluginExtension.java)
- [ ] Create unit tests [DefaultMeetingsPluginExtensionUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugin/internal/DefaultMeetingsPluginExtensionUnitTest.java)
- [ ] Create integration tests [DefaultMeetingsPluginExtensionIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugin/internal/DefaultMeetingsPluginExtensionIntegrationTest.java)
- [ ] Perform testing
- [ ] Commit update
