### ISSUE TITLE
TASK Create AgendaItem

### ISSUE THREAD

**Issue by mfisch2011** [mfisch2011/setools#8]
#### Task Steps/Actions
- [ ] Create implementation [AgendaItem.java](meetings-plugin/src/main/java/setools/gradle/plugin/AgendaItem.java)
- [ ] Create unit test [AgendaItemUnitTest.java](meetings-plugin/src/test/java/setools/gradle/plugin/AgendaItemUnitTest.java)
- [ ] Update [MeetingsPluginExtension.java](meetings-plugin/src/main/java/setools/gradle/plugin/MeetingsPluginExtension.java)
- [ ] Update [DefaultMeetingsPluginExtension.java](meetings-plugin/src/main/java/setools/gradle/plugin/internal/DefaultMeetingsPluginExtension.java)
- [ ] Update [DefaultMeetingsPluginExtensionIntegrationTest.java](meetings-plugin/src/integration-test/java/setools/gradle/plugin/DefaultMeetingsPluginExtensionIntegrationTest.java)
- [ ] Perform testing
- [ ] Commit update
